# Generated by Django 4.2.8 on 2023-12-13 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webappexample', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='user_id',
            new_name='user_email',
        ),
    ]
